#!/bin/bash
# =============================================================================
# KSM Main - Setup Nginx Host Reverse Proxy
# =============================================================================
# Script untuk setup reverse proxy di nginx host untuk devreport.ptkiansantang.com
# Usage: ./setup-nginx-host-proxy.sh [dev|prod]
# =============================================================================

set -e

ENVIRONMENT=${1:-dev}

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

if [ "$ENVIRONMENT" = "dev" ]; then
    DOMAIN="devreport.ptkiansantang.com"
    DEPLOY_PATH="/opt/ksm-main-dev"
    CONTAINER_PORT="8445"
    NGINX_CONTAINER="KSM-nginx-dev"
elif [ "$ENVIRONMENT" = "prod" ]; then
    DOMAIN="report.ptkiansantang.com"
    DEPLOY_PATH="/opt/ksm-main-prod"
    CONTAINER_PORT="8443"
    NGINX_CONTAINER="KSM-nginx-prod"
else
    echo -e "${RED}❌ Invalid environment. Use 'dev' or 'prod'${NC}"
    exit 1
fi

echo -e "${BLUE}🔧 KSM Main - Setup Nginx Host Reverse Proxy${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "Environment: ${YELLOW}$ENVIRONMENT${NC}"
echo -e "Domain: ${YELLOW}$DOMAIN${NC}"
echo -e "Container Port: ${YELLOW}$CONTAINER_PORT${NC}"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo -e "${YELLOW}⚠️  Warning: Script ini sebaiknya dijalankan sebagai root${NC}"
    echo "Gunakan: sudo $0 $ENVIRONMENT"
    read -p "Lanjutkan? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Check if nginx is installed on host
if ! command -v nginx >/dev/null 2>&1; then
    echo -e "${RED}❌ Nginx tidak terinstall di host!${NC}"
    echo ""
    echo "💡 Install nginx terlebih dahulu:"
    echo "   sudo apt update"
    echo "   sudo apt install -y nginx"
    exit 1
fi

# Check if nginx is running
if ! systemctl is-active --quiet nginx 2>/dev/null && ! pgrep -x nginx >/dev/null 2>&1; then
    echo -e "${YELLOW}⚠️  Nginx tidak berjalan di host${NC}"
    echo "   Starting nginx..."
    systemctl start nginx 2>/dev/null || service nginx start 2>/dev/null || true
    sleep 2
fi

# Determine nginx config directory
NGINX_SITES_AVAILABLE="/etc/nginx/sites-available"
NGINX_SITES_ENABLED="/etc/nginx/sites-enabled"
NGINX_CONF_DIR="/etc/nginx/conf.d"

# Create directories if they don't exist
if [ ! -d "$NGINX_SITES_AVAILABLE" ]; then
    mkdir -p "$NGINX_SITES_AVAILABLE"
fi
if [ ! -d "$NGINX_SITES_ENABLED" ]; then
    mkdir -p "$NGINX_SITES_ENABLED"
fi

# Step 1: Create nginx config file
echo -e "${BLUE}📋 Step 1: Creating nginx config file...${NC}"

CONFIG_FILE="$NGINX_SITES_AVAILABLE/$DOMAIN"
SSL_CERT="$DEPLOY_PATH/infrastructure/nginx/ssl/cert.pem"
SSL_KEY="$DEPLOY_PATH/infrastructure/nginx/ssl/key.pem"

# Check if SSL certificate exists
if [ ! -f "$SSL_CERT" ] || [ ! -f "$SSL_KEY" ]; then
    echo -e "${RED}❌ SSL certificate files not found!${NC}"
    echo "   Certificate: $SSL_CERT"
    echo "   Key: $SSL_KEY"
    echo ""
    echo "💡 Generate SSL certificate terlebih dahulu:"
    echo "   cd $DEPLOY_PATH"
    echo "   ./scripts/setup-ssl.sh $ENVIRONMENT your-email@example.com"
    exit 1
fi

# Create nginx config
cat > "$CONFIG_FILE" << EOF
# KSM Main - Nginx Reverse Proxy Configuration for $DOMAIN
# Auto-generated by setup-nginx-host-proxy.sh

# HTTP Server Block - Redirect to HTTPS
server {
    listen 80;
    server_name $DOMAIN;
    
    # Let's Encrypt validation (harus sebelum redirect)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    
    # Redirect semua HTTP ke HTTPS (kecuali Let's Encrypt validation)
    location / {
        return 301 https://\$host\$request_uri;
    }
}

# HTTPS Server Block - Reverse Proxy to Docker Container
server {
    listen 443 ssl http2;
    server_name $DOMAIN;
    
    # SSL Configuration
    ssl_certificate $SSL_CERT;
    ssl_certificate_key $SSL_KEY;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    
    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    
    # Reverse Proxy to Docker Container
    location / {
        proxy_pass https://localhost:$CONTAINER_PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        
        # SSL verification untuk upstream (optional, bisa di-disable jika self-signed)
        proxy_ssl_verify off;
    }
}
EOF

echo -e "${GREEN}✅ Nginx config file created: $CONFIG_FILE${NC}"

# Step 2: Enable site
echo ""
echo -e "${BLUE}📋 Step 2: Enabling site...${NC}"

# Create symlink if using sites-available/sites-enabled
if [ -d "$NGINX_SITES_ENABLED" ]; then
    if [ -L "$NGINX_SITES_ENABLED/$DOMAIN" ]; then
        echo "   Symlink already exists"
    else
        ln -s "$CONFIG_FILE" "$NGINX_SITES_ENABLED/$DOMAIN"
        echo -e "${GREEN}✅ Site enabled${NC}"
    fi
fi

# Step 3: Test nginx config
echo ""
echo -e "${BLUE}📋 Step 3: Testing nginx configuration...${NC}"

if nginx -t 2>&1 | grep -q "successful"; then
    echo -e "${GREEN}✅ Nginx configuration is valid${NC}"
else
    echo -e "${RED}❌ Nginx configuration has errors!${NC}"
    nginx -t 2>&1 || true
    echo ""
    echo "💡 Fix errors above before continuing"
    exit 1
fi

# Step 4: Reload nginx
echo ""
echo -e "${BLUE}📋 Step 4: Reloading nginx...${NC}"

if systemctl reload nginx 2>/dev/null || service nginx reload 2>/dev/null; then
    echo -e "${GREEN}✅ Nginx reloaded successfully${NC}"
else
    echo -e "${YELLOW}⚠️  Reload failed, trying restart...${NC}"
    systemctl restart nginx 2>/dev/null || service nginx restart 2>/dev/null || true
    sleep 2
    echo -e "${GREEN}✅ Nginx restarted${NC}"
fi

# Step 5: Verify
echo ""
echo -e "${BLUE}📋 Step 5: Verifying setup...${NC}"

# Check if nginx is listening on port 443
if lsof -i :443 >/dev/null 2>&1 || ss -tlnp | grep -q ":443 "; then
    echo -e "${GREEN}✅ Nginx is listening on port 443${NC}"
else
    echo -e "${YELLOW}⚠️  Nginx might not be listening on port 443${NC}"
fi

# Test SSL connection
if command -v openssl >/dev/null 2>&1; then
    echo "Testing SSL connection..."
    SSL_OUTPUT=$(echo | openssl s_client -connect "$DOMAIN:443" -servername "$DOMAIN" 2>&1 || true)
    
    if echo "$SSL_OUTPUT" | grep -q "subject="; then
        CERT_SUBJECT=$(echo "$SSL_OUTPUT" | grep -A 1 "subject=" | head -2 | tail -1 | sed 's/^[[:space:]]*//' || echo "")
        echo "   Certificate subject: $CERT_SUBJECT"
        
        if echo "$CERT_SUBJECT" | grep -q "$DOMAIN"; then
            echo -e "${GREEN}✅ SSL certificate is correct!${NC}"
        else
            echo -e "${YELLOW}⚠️  SSL certificate might not match domain${NC}"
        fi
    fi
fi

echo ""
echo -e "${GREEN}✅ Setup completed!${NC}"
echo ""
echo "💡 Test your site:"
echo "   curl -I https://$DOMAIN"
echo "   openssl s_client -connect $DOMAIN:443 -servername $DOMAIN"
echo ""
echo "📝 Configuration file: $CONFIG_FILE"
echo "   To edit: sudo nano $CONFIG_FILE"
echo "   To disable: sudo rm $NGINX_SITES_ENABLED/$DOMAIN && sudo nginx -s reload"

